In [7]:
import pandas as pd

ci_filepath = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv"

cc_filepath = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildCharacteristics.csv"

identifiers = pd.read_csv(ci_filepath, parse_dates=['PersonBirthDate', 'PersonDeathDate'])



characteristics = pd.read_csv(cc_filepath)

identifiers.dtypes

Unnamed: 0                          int64
LAchildID                          object
UPN                                object
FormerUPN                         float64
UPNunknown                        float64
PersonBirthDate            datetime64[ns]
ExpectedPersonBirthDate            object
GenderCurrent                       int64
PersonDeathDate                    object
dtype: object

In [2]:
#identifiers.info()
identifiers['PersonBirthDate_dt'] = pd.to_datetime(identifiers['PersonBirthDate'], format="%Y-%m-%d")

identifiers['ExpectedPersonBirthDate_dt'] = pd.to_datetime(identifiers['ExpectedPersonBirthDate'], format="%Y-%m-%d")

identifiers['ExpectedPersonBirthDate_dt'] = pd.to_datetime(identifiers['ExpectedPersonBirthDate'], format="%Y-%m-%d")
identifiers.head()

,Unnamed: 0,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate,PersonBirthDate_dt,ExpectedPersonBirthDate_dt
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN,2019-12-06,NaT
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN,2011-04-27,NaT
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN,2017-06-06,2019-12-06
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN,2014-10-03,NaT
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN,2019-09-25,NaT

In [3]:
identifiers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  332 non-null    int64
 1   LAchildID                   332 non-null    object
 2   UPN                         332 non-null    object
 3   FormerUPN                   0 non-null      float64
 4   UPNunknown                  0 non-null      float64
 5   PersonBirthDate             332 non-null    object
 6   ExpectedPersonBirthDate     7 non-null      object
 7   GenderCurrent               332 non-null    int64
 8   PersonDeathDate             21 non-null     object
 9   PersonBirthDate_dt          332 non-null    datetime64[ns]
 10  ExpectedPersonBirthDate_dt  7 non-null      datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(5)
memory usage: 28.7+ KB

In [4]:
# NaN not a number, NaT not a time, Na/pd.NA generic null
# identifiers.info()

# strftime formats
identifiers['PersonBirthDate_dt'] = pd.to_datetime(identifiers['PersonBirthDate'], format="%Y-%m-%d")

identifiers["ExpectedPersonBirthDate_dt"] = pd.to_datetime(identifiers['ExpectedPersonBirthDate'], format="%Y-%m-%d")

identifiers["PersonDeathDate_dt"] = pd.to_datetime(identifiers["PersonDeathDate"], format="%Y-%m-%d", errors="coerce")

identifiers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  332 non-null    int64
 1   LAchildID                   332 non-null    object
 2   UPN                         332 non-null    object
 3   FormerUPN                   0 non-null      float64
 4   UPNunknown                  0 non-null      float64
 5   PersonBirthDate             332 non-null    object
 6   ExpectedPersonBirthDate     7 non-null      object
 7   GenderCurrent               332 non-null    int64
 8   PersonDeathDate             21 non-null     object
 9   PersonBirthDate_dt          332 non-null    datetime64[ns]
 10  ExpectedPersonBirthDate_dt  7 non-null      datetime64[ns]
 11  PersonDeathDate_dt          20 non-null     datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(5)
memory usage: 31.3+ KB

In [5]:
child_info = pd.DataFrame({'ChildId':['id1', 'id2', 'id3', 'id4', 'id5'],
                           'Age at contact':[6, 12, 11, 1, 19],
                           'SEX':['M', 'm', 'F', '', 'F'],
                           'Birthday':['01/01/2002', '02/02/2003', pd.NA, '03/03/2023', '06/01/2012'],
                           'CP Plan?':['Y', 'n', 'N', 'No', 'yES'],})

child_info

  ChildId  Age at contact SEX    Birthday CP Plan?
0     id1               6   M  01/01/2002        Y
1     id2              12   m  02/02/2003        n
2     id3              11   F        <NA>        N
3     id4               1      03/03/2023       No
4     id5              19   F  06/01/2012      yES

In [6]:
child_info = pd.DataFrame({'ChildId':['id1', 'id2', 'id3', 'id4', 'id5'],
                           'Age at contact':[6, 12, 11, 1, 19],
                           'SEX':['M', 'm', 'F', '', 'F'],
                           'Birthday':['01/01/2002', '02/02/2003', pd.NA, '03/03/2023', '06/01/2012'],
                           'CP Plan?':['Y', 'n', 'N', 'No', 'yES'],})

nhs_numbers = pd.DataFrame([{'ChildId':'id1',
                             'NHS Number':'303'},
                             {'ChildId':'id2',
                              'NHS Number':'3u5029'},
                            {'ChildId':'id3',
                            'NHS Number': 'gqw3',},
                            {'ChildId':'id4',
                            'NHS Number': 'avsgvb',},
                            {'ChildId':'id5',
                            'NHS Number': 'varwvw',},
                             ])

nhs_numbers

  ChildId NHS Number
0     id1        303
1     id2     3u5029
2     id3       gqw3
3     id4     avsgvb
4     id5     varwvw

In [7]:
#child_info['Age'] = child_info['Birthday_dt'].apply(lambda row: relativedelta(pd.to_datetime('today'), row).years)

child_info

  ChildId  Age at contact SEX    Birthday CP Plan?
0     id1               6   M  01/01/2002        Y
1     id2              12   m  02/02/2003        n
2     id3              11   F        <NA>        N
3     id4               1      03/03/2023       No
4     id5              19   F  06/01/2012      yES

In [8]:
import openpyxl



filepath = r"https://github.com/data-to-insight/ERN-sessions/raw/main/data/small%20excel.xlsx"

df = pd.read_excel(filepath, sheet_name=None)

#print(df_dict.keys)
df

{'Child Data':   ChildID Sex        DOB EHCP issued
 0     id1   M 2014-12-05           N
 1     id6   m 2016-01-06           n
 2     id4   m 2013-11-09           Y
 3     id3   F 2022-12-24           Y
 4     id5   F 2020-01-15         NaN
 5     id7   f 2022-09-17           y,
 'Child extras':   ChildID  Assessment Code
 0     id1                1
 1     id5                2
 2     id4                3
 3     id3                4
 4     id6                5
 5     id7                6,
 'Sheet3':    Assessment Code Assessment Outcome
 0                1                  Y
 1                2                  N
 2                3                  N
 3                4                  n
 4                5                  y
 5                6                  N}

In [9]:
print(child_info.columns)
print(nhs_numbers.columns)

child_info_1 = pd.merge(child_info,nhs_numbers,left_on='ChildId',right_on='ChildId', how='left')

child_info_1

Index(['ChildId', 'Age at contact', 'SEX', 'Birthday', 'CP Plan?'], dtype='object')
Index(['ChildId', 'NHS Number'], dtype='object')

  ChildId  Age at contact SEX    Birthday CP Plan? NHS Number
0     id1               6   M  01/01/2002        Y        303
1     id2              12   m  02/02/2003        n     3u5029
2     id3              11   F        <NA>        N       gqw3
3     id4               1      03/03/2023       No     avsgvb
4     id5              19   F  06/01/2012      yES     varwvw

In [10]:
print(identifiers.columns)
print(characteristics.columns)

identifiers_1 = identifiers.merge(characteristics, on='LAchildID', how='left')

identifiers_1

Index(['Unnamed: 0', 'LAchildID', 'UPN', 'FormerUPN', 'UPNunknown',
       'PersonBirthDate', 'ExpectedPersonBirthDate', 'GenderCurrent',
       'PersonDeathDate', 'PersonBirthDate_dt', 'ExpectedPersonBirthDate_dt',
       'PersonDeathDate_dt'],
      dtype='object')
Index(['Unnamed: 0', 'LAchildID', 'Ethnicity'], dtype='object')

,Unnamed: 0_x,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate,PersonBirthDate_dt,ExpectedPersonBirthDate_dt,PersonDeathDate_dt,Unnamed: 0_y,Ethnicity
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN,2019-12-06,NaT,NaT,0,WIRT
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN,2011-04-27,NaT,NaT,1,WROM
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN,2017-06-06,2019-12-06,NaT,2,AOTH
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN,2014-10-03,NaT,NaT,3,MWBC
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN,2019-09-25,NaT,NaT,4,APKN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,327,RND000112711501,A465246916125,NaN,NaN,2010-07-07,NaN,2,NaN,2010-07-07,NaT,NaT,327,WOTH
328,328,RND000513120794,A540014111973,NaN,NaN,2018-08-14,NaN,2,NaN,2018-08-14,NaT,NaT,328,WROM
329,329,RND000541643134,A549582689058,NaN,NaN,2021-12-09,NaN,51,NaN,2021-12-09,NaT,NaT,329,BCRB
330,330,RND000404939452,A889492349196,NaN,NaN,2013-07-23,NaN,2,NaN,2013-07-23,NaT,NaT,330,AIND
331,331,RND000589802835,A877624860226,NaN,NaN,2021-10-25,NaN,9,NaN,2021-10-25,NaT,NaT,331,WBRI

In [11]:
# pip install openpyxl
import openpyxl

filepath = r"https://github.com/data-to-insight/ERN-sessions/raw/main/data/small%20excel.xlsx"

# with an excel, if oyu're reading multiple sheets, they come stored in a dictionary
# with sheet names as keys and dfs as values
df_dict = pd.read_excel(filepath, sheet_name=None)

print(df_dict.keys())

df_dict['Child Data']

dict_keys(['Child Data', 'Child extras', 'Sheet3'])

  ChildID Sex        DOB EHCP issued
0     id1   M 2014-12-05           N
1     id6   m 2016-01-06           n
2     id4   m 2013-11-09           Y
3     id3   F 2022-12-24           Y
4     id5   F 2020-01-15         NaN
5     id7   f 2022-09-17           y

In [12]:
print(child_info.columns)

print(nhs_numbers.columns)

# if the columns names are the same for both tables you can simply use on='ChildID' rather than specifying a left and right on
# different types of merge, left, right, inner, outer
child_info = pd.merge(child_info, nhs_numbers, left_on='ChildId', right_on='ChildId', how='left')

child_info

Index(['ChildId', 'Age at contact', 'SEX', 'Birthday', 'CP Plan?'], dtype='object')
Index(['ChildId', 'NHS Number'], dtype='object')

  ChildId  Age at contact SEX    Birthday CP Plan? NHS Number
0     id1               6   M  01/01/2002        Y        303
1     id2              12   m  02/02/2003        n     3u5029
2     id3              11   F        <NA>        N       gqw3
3     id4               1      03/03/2023       No     avsgvb
4     id5              19   F  06/01/2012      yES     varwvw

In [13]:
identifiers = identifiers.merge(characteristics, on=['LAchildID', 'Unnamed: 0'], how='left')

identifiers

,Unnamed: 0,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate,PersonBirthDate_dt,ExpectedPersonBirthDate_dt,PersonDeathDate_dt,Ethnicity
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN,2019-12-06,NaT,NaT,WIRT
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN,2011-04-27,NaT,NaT,WROM
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN,2017-06-06,2019-12-06,NaT,AOTH
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN,2014-10-03,NaT,NaT,MWBC
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN,2019-09-25,NaT,NaT,APKN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,327,RND000112711501,A465246916125,NaN,NaN,2010-07-07,NaN,2,NaN,2010-07-07,NaT,NaT,WOTH
328,328,RND000513120794,A540014111973,NaN,NaN,2018-08-14,NaN,2,NaN,2018-08-14,NaT,NaT,WROM
329,329,RND000541643134,A549582689058,NaN,NaN,2021-12-09,NaN,51,NaN,2021-12-09,NaT,NaT,BCRB
330,330,RND000404939452,A889492349196,NaN,NaN,2013-07-23,NaN,2,NaN,2013-07-23,NaT,NaT,AIND
331,331,RND000589802835,A877624860226,NaN,NaN,2021-10-25,NaN,9,NaN,2021-10-25,NaT,NaT,WBRI

In [14]:
df = df_dict['Child Data'].merge(df_dict['Child extras'], how='left', on='ChildID').merge(df_dict['Sheet3'], how='left', on='Assessment Code')

df

  ChildID Sex        DOB EHCP issued  Assessment Code Assessment Outcome
0     id1   M 2014-12-05           N                1                  Y
1     id6   m 2016-01-06           n                5                  y
2     id4   m 2013-11-09           Y                3                  N
3     id3   F 2022-12-24           Y                4                  n
4     id5   F 2020-01-15         NaN                2                  N
5     id7   f 2022-09-17           y                6                  N

In [15]:
identifiers = identifiers.merge(characteristics, on=['LAchildID', 'Unnamed: 0'], how='left')

identifiers
df = df_dict['Child Data'].merge(df_dict['Child extras'], how='left', on='ChildID').merge(df_dict['Sheet3'], how='left', on='Assessment Code')

df

  ChildID Sex        DOB EHCP issued  Assessment Code Assessment Outcome
0     id1   M 2014-12-05           N                1                  Y
1     id6   m 2016-01-06           n                5                  y
2     id4   m 2013-11-09           Y                3                  N
3     id3   F 2022-12-24           Y                4                  n
4     id5   F 2020-01-15         NaN                2                  N
5     id7   f 2022-09-17           y                6                  N

In [16]:
import pandas as pd
from dateutil.relativedelta import relativedelta

In [17]:
child_info

  ChildId  Age at contact SEX    Birthday CP Plan? NHS Number
0     id1               6   M  01/01/2002        Y        303
1     id2              12   m  02/02/2003        n     3u5029
2     id3              11   F        <NA>        N       gqw3
3     id4               1      03/03/2023       No     avsgvb
4     id5              19   F  06/01/2012      yES     varwvw

In [18]:
import numpy as np

In [19]:
child_info['Birthday_dt'] = pd.to_datetime(child_info['Birthday'], dayfirst=True, errors='coerce')

child_info['Birthday_dt'] = pd.to_datetime(child_info['Birthday'], errors='coerce')

#child_info['Birthday_dt'] = child_info['Birthday_dt'].replace({pd.NaT: np.nan})


child_info
#child_info.info()

  ChildId  Age at contact SEX    Birthday CP Plan? NHS Number Birthday_dt
0     id1               6   M  01/01/2002        Y        303  2002-01-01
1     id2              12   m  02/02/2003        n     3u5029  2003-02-02
2     id3              11   F        <NA>        N       gqw3         NaT
3     id4               1      03/03/2023       No     avsgvb  2023-03-03
4     id5              19   F  06/01/2012      yES     varwvw  2012-06-01

In [20]:
#child_info['Age'] = child_info['Birthday_dt'].apply(lambda row: relativedelta(pd.to_datetime('today'), row).years)

#child_info

child_info['Age'] = child_info['Birthday_dt'].apply(lambda d: relativedelta(pd.Timestamp.today(), d).years if pd.notnull(d) else None)

child_info

,ChildId,Age at contact,SEX,Birthday,CP Plan?,NHS Number,Birthday_dt,Age
0,id1,6,M,01/01/2002,Y,303,2002-01-01,23.0
1,id2,12,m,02/02/2003,n,3u5029,2003-02-02,22.0
2,id3,11,F,<NA>,N,gqw3,NaT,NaN
3,id4,1,,03/03/2023,No,avsgvb,2023-03-03,2.0
4,id5,19,F,06/01/2012,yES,varwvw,2012-06-01,13.0

In [27]:
child_info

under_5_cond = child_info['Age'] < 5

under_5_cond

under_5_df = child_info[under_5_cond]

under_5_df

#negation condition

over_5_df = child_info[~under_5_cond]

over_5_df

# 5 and under

ages_13_and_under_cond = child_info['Age'] <= 13

ages_13_and_under_df = child_info[ages_13_and_under_cond]
ages_13_and_under_df

,ChildId,Age at contact,SEX,Birthday,CP Plan?,NHS Number,Birthday_dt,Age
3,id4,1,,03/03/2023,No,avsgvb,2023-03-03,2.0
4,id5,19,F,06/01/2012,yES,varwvw,2012-06-01,13.0

In [29]:
# | or, & and

over_5_cond = child_info['Age'] > 5
under_20_cond = child_info['Age'] < 20
between_5_and_20 = child_info[under_5_cond & under_20_cond]

between_5_and_20


not_between_5_20 = child_info[(child_info['Age'] <5) | (child_info['Age'] > 20)]

not_between_5_20

,ChildId,Age at contact,SEX,Birthday,CP Plan?,NHS Number,Birthday_dt,Age
0,id1,6,M,01/01/2002,Y,303,2002-01-01,23.0
1,id2,12,m,02/02/2003,n,3u5029,2003-02-02,22.0
3,id4,1,,03/03/2023,No,avsgvb,2023-03-03,2.0

In [31]:
under_5_cond = child_info[child_info['Age'] < 5]

under_5_cond

  ChildId  Age at contact SEX    Birthday CP Plan? NHS Number Birthday_dt  Age
3     id4               1      03/03/2023       No     avsgvb  2023-03-03  2.0

In [1]:
# less than condition <
under_5_cond = child_info['Age'] < 5 

under_5_df = child_info[under_5_cond]

# ~ negation condition
over_5_df = child_info[~under_5_cond]

# 5 and under -> <=
ages_5_and_under_cond = child_info['Age'] <= 5
ages_5_and_under_df = child_info[ages_5_and_under_cond]

ages_5_and_under_df

NameError: name 'child_info' is not defined