In [24]:
import pandas as pd

filepath = "https://github.com/data-to-insight/ERN-sessions/raw/main/data/903_xlsx_errors.xlsx"

dfs = pd.read_excel(filepath, sheet_name=None)

#dfs.keys()

dfs['header'].head()
dfs['header'].dtypes

CHILD      object
SEX         int64
DOB        object
ETHNIC     object
UPN        object
MOTHER    float64
MC_DOB     object
dtype: object

In [2]:
import pandas as pd
from dateutil.relativedelta import relativedelta

In [3]:
# a dictionary of lists
child_info = pd.DataFrame({'ChildId':['id1', 'id2', 'id3', 'id4', 'id5'],
                           'Age at contact':[6, 12, 11, 1, 19],
                           'SEX':['M', 'm', 'F', '', 'F'],
                           'Birthday':['01/01/2002', '02/02/2003', '01/01/2000', '03/03/2023', '06/01/2012'],
                           'CP Plan?':['Y', 'n', 'N', 'No', 'yES'],})

nhs_numbers = pd.DataFrame([{'ChildId':'id1',
                             'NHS Number':'303'},
                             {'ChildId':'id2',
                              'NHS Number':'3u5029'},
                            {'ChildId':'id3',
                            'NHS Number': 'gqw3',},
                            {'ChildId':'id4',
                            'NHS Number': 'avsgvb',},
                            {'ChildId':'id5',
                            'NHS Number': 'varwvw',},
                             ])

child_info['Birthday_dt'] = pd.to_datetime(child_info['Birthday'], dayfirst=True, errors='coerce')

In [4]:
#child_info['Age'] = child_info['Birthday_dt'].apply(lambda row: relativedelta(pd.to_datetime('today'), row).years)

#child_info

child_info['Age'] = child_info['Birthday_dt'].apply(lambda d: relativedelta(pd.Timestamp.today(), d).years if pd.notnull(d) else None)

child_info

  ChildId  Age at contact SEX    Birthday CP Plan? Birthday_dt  Age
0     id1               6   M  01/01/2002        Y  2002-01-01   23
1     id2              12   m  02/02/2003        n  2003-02-02   22
2     id3              11   F  01/01/2000        N  2000-01-01   25
3     id4               1      03/03/2023       No  2023-03-03    2
4     id5              19   F  06/01/2012      yES  2012-01-06   13

In [5]:
# less than condition <
under_5_cond = child_info['Age'] < 5 

under_5_df = child_info[under_5_cond]

# ~ negation condition
over_5_df = child_info[~under_5_cond]

# 5 and under -> <=
ages_5_and_under_cond = child_info['Age'] <= 5
ages_5_and_under_df = child_info[ages_5_and_under_cond]

ages_5_and_under_df

  ChildId  Age at contact SEX    Birthday CP Plan? Birthday_dt  Age
3     id4               1      03/03/2023       No  2023-03-03    2

In [6]:
# | or, & and

over_5_cond = child_info['Age'] > 5
under_20_cond = child_info['Age'] < 20

between_5_20 = child_info[over_5_cond & under_20_cond]

not_between_5_20 = child_info[(child_info['Age'] < 5) | (child_info['Age'] > 20)]

In [7]:
filepath = "https://github.com/data-to-insight/ERN-sessions/raw/main/data/903_xlsx_errors.xlsx"

In [8]:
import pandas as pd

filepath = "https://github.com/data-to-insight/ERN-sessions/raw/main/data/903_xlsx_errors.xlsx"

dfs = pd.read_excel(filepath, sheet_name=None)

# dfs.keys()

# dfs['header'].info()

dfs['header'].head()

    CHILD  SEX         DOB ETHNIC            UPN  MOTHER MC_DOB
0  566910    2  27/03/2008   WROM  D051910639385     NaN    NaN
1  384923    2  09/09/2011   REFU  L034811502612     NaN    NaN
2  709901    1  14/02/2013   ABAN  Y021751958510     NaN    NaN
3  550084    2  04/05/2008   AOTH  R095578985099     NaN    NaN
4  710229    2  15/04/2002   REFU  Z095096287583     NaN    NaN

In [9]:
header = dfs['header']

# ssda903 102 - date of birth is not a valid date

# coercing errors returns NATs for invalid dates
# if I slice out all NaTs - I have all the invalid dates!
header['DOB_dt'] = pd.to_datetime(header['DOB'], format="%d/%m/%Y", errors='coerce')

# .isna() rewutnrs true where the value in a row in a column is an Na
invalid_dobs = header['DOB_dt'].isna()
error_rows = header[invalid_dobs]

error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [10]:
# 115 - Date of Local Authority's (LA) decision that a child 
# should be placed for adoption is not a valid date."

# select the placed for adation table from dfs, 
# convert the correct column to a datetime, 
# make the slice

In [11]:
#Rueben
# 115 - Date of Local Authority's (LA) decision that a child 
# should be placed for adoption is not a valid date."

# select the placed for adoption table from dfs, 
# convert the correct column to a datetime, 
# make the slice

adoption = dfs['placed_for_adoption']

adoption['DATE_PLACED_dt'] = pd.to_datetime(adoption['DATE_PLACED'], format="%d/%m/%Y", errors='coerce')

invalid_placed_for_adoption_dates = adoption['DATE_PLACED_dt'].isna()

p4a_errors = adoption[invalid_placed_for_adoption_dates]

p4a_errors

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt
29,bad_entry_1,Not a date,This isn't a valid date,This also isn't a date,oop,NaT

In [12]:
# .isin() -> returns true where a column has a value in a list... it is in the list
# 103 - The ethnicity code is either not valid or has not been entered.

ethncity_codes = [
        "WBRI",
        "WIRI",
        "WOTH",
        "WIRT",
        "WROM",
        "MWBC",
        "MWBA",
        "MWAS",
        "MOTH",
        "AIND",
        "APKN",
        "ABAN",
        "AOTH",
        "BCRB",
        "BAFR",
        "BOTH",
        "CHNE",
        "OOTH",
        "REFU",
        "NOBT",
    ]
# ~ 
error_rows = header[~header['ETHNIC'].isin(ethncity_codes)]
error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [13]:
dfs.keys()

dict_keys(['ad1', 'episodes', 'header', 'missing', 'oc2', 'oc3', 'placed_for_adoption', 'previous_permenance', 'reviews', 'uasc'])

In [14]:
p4a = dfs['placed_for_adoption']

p4a.head()

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt
0,988635,15/06/2013,22/11/2015,07/04/2017,XXX,2015-11-22
1,161125,24/07/2002,08/05/2015,24/02/2018,XXX,2015-05-08
2,590545,24/11/2008,12/09/2015,23/04/2017,XXX,2015-09-12
3,757606,12/12/2003,16/09/2015,23/02/2018,XXX,2015-09-16
4,921450,11/10/2006,02/03/2015,15/08/2017,XXX,2015-03-02

In [15]:
# 114 - Data entry to record the status of former carer(s) of an adopted child is invalid.
# When we do an isin we need to check the datatype of the list is the same as the values
# valid codes 0, 1
# table is ad1

In [16]:
merged_df = p4a.merge(header[['CHILD', 'DOB_dt']], on='CHILD', how='left', suffixes=[None, '_head'])

merged_df

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt,DOB_dt
0,988635,15/06/2013,22/11/2015,07/04/2017,XXX,2015-11-22,2013-06-15
1,161125,24/07/2002,08/05/2015,24/02/2018,XXX,2015-05-08,2002-07-24
2,590545,24/11/2008,12/09/2015,23/04/2017,XXX,2015-09-12,2008-11-24
3,757606,12/12/2003,16/09/2015,23/02/2018,XXX,2015-09-16,2003-12-12
4,921450,11/10/2006,02/03/2015,15/08/2017,XXX,2015-03-02,2006-10-11
5,4022,11/05/2001,11/11/2015,30/12/2017,XXX,2015-11-11,2001-05-11
6,127650,24/02/2013,05/09/2015,22/06/2017,XXX,2015-09-05,2013-02-24
7,624227,04/07/2008,27/01/2015,24/09/2017,XXX,2015-01-27,2008-07-04
8,711458,06/05/2009,19/03/2015,27/11/2017,XXX,2015-03-19,2009-05-06
9,549562,25/07/2009,30/10/2015,22/11/2017,XXX,2015-10-30,2009-07-25
10,83008,05/06/2005,06/02/2015,16/10/2017,XXX,2015-02-06,2005-06-05
11,764585,01/06/2011,17/05/2015,08/12/2017,XXX,2015-05-17,2011-06-01
12,432916,28/01/2002,02/08/2015,08/03/2018,XXX,2015-08-02,2002-01-28
13,232351,08/11/2006,09/10/2015,02/08/2017,XXX,2015-10-09,2006-11-08
14,682447,10/07/2008,02/01/2015,03/11/2017,XXX,2015-01-02,2008-07-10
15,979106,11/04/2013,04/02/2015,12/01/2018,XXX,2015-02-04,2013-04-11
16,177224,16/04/2008,17/01/2015,02/11/2017,XXX,2015-01-17,2008-04-16
17,150309,12/12/2003,22/04/2015,10/04/2017,XXX,2015-04-22,2003-12-12
18,912765,25/04/2007,24/06/2015,02/05/2017,XXX,2015-06-24,2007-04-25
19,258758,09/01/2012,10/06/2015,22/04/2017,XXX,2015-06-10,2012-01-09
20,183392,03/09/2012,28/03/2015,02/03/2018,XXX,2015-03-28,2012-09-03
21,882662,24/07/2003,26/09/2015,22/11/2017,XXX,2015-09-26,2003-07-24
22,867782,20/09/2002,02/09/2015,04/04/2017,XXX,2015-09-02,2002-09-20
23,398366,07/06/2010,17/03/2015,29/05/2017,XXX,2015-03-17,2010-06-07
24,465676,09/05/2012,30/05/2015,29/05/2017,XXX,2015-05-30,2012-05-09
25,553789,15/07/2010,06/12/2015,08/02/2018,XXX,2015-12-06,2010-07-15
26,667633,26/10/2007,01/06/2015,02/05/2017,XXX,2015-06-01,2007-10-26
27,940956,02/04/2011,30/01/2015,29/11/2017,XXX,2015-01-30,2011-04-02
28,458257,21/02/2007,23/08/2015,03/01/2018,XXX,2015-08-23,2007-02-21
29,bad_entry_1,Not a date,This isn't a valid date,This also isn't a date,oop,NaT,NaT

In [17]:
# 184 - Date of decision that a child should be placed for adoption is before the child was born.
# return rows where DOB after DATE_PLACED -> DOB > DATE_PLACED

merged_df = p4a.merge(header[['CHILD', 'DOB_dt']], on='CHILD', how='left', suffixes=[None, '_head'])

error_rows = merged_df[merged_df["DOB_dt"] > merged_df['DATE_PLACED_dt']]

error_rows

Empty DataFrame
Columns: [CHILD, DOB, DATE_PLACED, DATE_PLACED_CEASED, REASON_PLACED_CEASED, DATE_PLACED_dt, DOB_dt]
Index: []

In [18]:
# 302 - First episode starts before child was born.
# tables are header and episodes
# DOB from header and DECOM from episodes

In [19]:
header = dfs['header']

# ssda903 102 - date of birth is not a valid date

# coercing errors returns NATs for invalid dates
# if I slice out all NaTs - I have all the invalid dates!
header['DOB_dt'] = pd.to_datetime(header['DOB'], format="%d/%m/%Y", errors='coerce')

# .isna() rewutnrs true where the value in a row in a column is an Na
invalid_dobs = header['DOB_dt'].isna()
error_rows = header[invalid_dobs]

error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [20]:
# 302 - First episode starts before child was born.
# tables are header and episodes
# DOB from header and DECOM from episodes

episodes = dfs['episodes']

episodes['DECOM_dt'] = pd.to_datetime(episodes['DECOM'], format="%Y-%m-%d", errors='coerce')

# sorts values
episodes = episodes.sort_values(['CHILD', 'DECOM'], ascending=True)

# drops duplicates
episodes.drop_duplicates('CHILD', keep='first', inplace=True)

df = pd.merge(episodes, header, how='left', on='CHILD', suffixes=['_epi', '_hdr'])

error_rows = df[df['DECOM'] < df['DOB']]
error_rows

,CHILD,DECOM,RNE,LS,CIN,PLACE,PLACE_PROVIDER,DEC,REC,REASON_PLACE_CHANGE,...,PL_POST,URN,DECOM_dt,SEX,DOB,ETHNIC,UPN,MOTHER,MC_DOB,DOB_dt
0,32,12/02/2017,T,J1,N3,K2,PR1,15/04/2017,E3,NaN,...,WI5 9CC,7876040,NaT,2,15/02/2008,WROM,N083906900567,NaN,NaN,2008-02-15
1,982,07/10/2017,T,E1,N7,H5,PR4,15/10/2017,X1,APPRR,...,WB15 6HK,3183884,NaT,2,21/11/2010,BOTH,V078668886875,NaN,NaN,2010-11-21
2,1243,02/01/2017,L,V4,N5,Z1,PR0,18/05/2017,E9,NaN,...,WC30 9OS,7270736,NaT,1,19/08/2002,OOTH,U000920739425,NaN,NaN,2002-08-19
3,1407,07/06/2017,P,L2,N3,U3,PR5,07/10/2017,X1,CUSTOD,...,WI24 8QE,8380497,NaT,2,26/06/2003,AOTH,Y010365886691,NaN,NaN,2003-06-26
4,2431,01/02/2018,P,L2,N3,A3,PR5,NaN,E14,NaN,...,WT6 3JM,8470650,NaT,1,19/01/2001,MWBC,W079251598684,NaN,NaN,2001-01-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2112,991062,06/09/2016,T,J1,N3,U6,PR1,07/04/2017,E14,NaN,...,WC22 6IS,7181943,NaT,1,15/03/2013,CHNE,R066104779187,NaN,NaN,2013-03-15
2116,995881,02/01/2017,P,L1,N5,U6,PR4,20/01/2018,X1,PLACE,...,WO14 3FR,5386118,NaT,2,03/11/2004,REFU,X032007250701,NaN,NaN,2004-11-03
2118,997201,07/06/2017,T,L3,N4,A5,PR1,NaN,X1,NaN,...,WN12 2KE,2276120,NaT,1,24/05/2006,WBRI,X075905131541,NaN,NaN,2006-05-24
2120,998192,08/07/2017,T,C2,N2,U1,PR4,NaN,X1,CREQB,...,WA22 6DB,1505258,NaT,2,25/07/2007,AIND,P044466275725,NaN,NaN,2007-07-25
2121,998777,11/10/2015,P,C2,N2,U1,PR2,17/03/2018,X1,CLOSE,...,WJ7 5PQ,1112628,NaT,1,16/11/2007,WBRI,X016147706879,NaN,NaN,2007-11-16

In [21]:
# sort_values()
# drop_duplicates()
 
epi_ordered = episodes.sort_values(['CHILD', 'DECOM_dt'], ascending=True)
 
first_episode = epi_ordered.drop_duplicates('CHILD', keep='first')
 
first_episode

,CHILD,DECOM,RNE,LS,CIN,PLACE,PLACE_PROVIDER,DEC,REC,REASON_PLACE_CHANGE,HOME_POST,PL_POST,URN,DECOM_dt
4801,32,12/02/2017,T,J1,N3,K2,PR1,15/04/2017,E3,NaN,ED8 1OX,WI5 9CC,7876040,NaT
4042,982,07/10/2017,T,E1,N7,H5,PR4,15/10/2017,X1,APPRR,EF24 4OP,WB15 6HK,3183884,NaT
437,1243,02/01/2017,L,V4,N5,Z1,PR0,18/05/2017,E9,NaN,EC5 5MZ,WC30 9OS,7270736,NaT
1796,1407,07/06/2017,P,L2,N3,U3,PR5,07/10/2017,X1,CUSTOD,EK9 2HR,WI24 8QE,8380497,NaT
3851,2431,01/02/2018,P,L2,N3,A3,PR5,NaN,E14,NaN,EZ17 3GY,WT6 3JM,8470650,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,997201,07/06/2017,T,L3,N4,A5,PR1,NaN,X1,NaN,EC16 9ZF,WN12 2KE,2276120,NaT
2766,997445,20/06/2016,P,J1,N2,U3,PR3,24/09/2017,E48,NaN,EP2 2VO,WE6 1FZ,3786993,NaT
155,998192,08/07/2017,T,C2,N2,U1,PR4,NaN,X1,CREQB,EL26 9FW,WA22 6DB,1505258,NaT
156,998777,11/10/2015,P,C2,N2,U1,PR2,17/03/2018,X1,CLOSE,ER24 5VS,WJ7 5PQ,1112628,NaT
323,999397,17/02/2017,L,L1,N7,P2,PR1,29/08/2017,X1,NaN,EC5 2KK,WV19 3SY,3534004,NaT