In [1]:
import pandas as pd

filepath = "https://github.com/data-to-insight/ERN-sessions/raw/main/data/903_xlsx_errors.xlsx"

dfs = pd.read_excel(filepath, sheet_name=None)

#dfs.keys()

dfs['header'].head()

    CHILD  SEX         DOB ETHNIC            UPN  MOTHER MC_DOB
0  566910    2  27/03/2008   WROM  D051910639385     NaN    NaN
1  384923    2  09/09/2011   REFU  L034811502612     NaN    NaN
2  709901    1  14/02/2013   ABAN  Y021751958510     NaN    NaN
3  550084    2  04/05/2008   AOTH  R095578985099     NaN    NaN
4  710229    2  15/04/2002   REFU  Z095096287583     NaN    NaN

In [2]:
header = dfs['header']

#ssda903 102 - date of birth not a valid date

header

header['DOB_dt'] = pd.to_datetime(header['DOB'], format="%d/%m/%Y", errors= 'coerce')

header

invalid_dobs = header['DOB_dt'].isna()

error_rows = header[invalid_dobs]

error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [3]:
# 115 - Date of Local Authority's (LA) decision that a child 
# should be placed for adoption is not a valid date."

# select the placed for adation table from dfs, 
# convert the correct column to a datetime, 
# make the slice

In [4]:
dfs.keys()


dfs['placed_for_adoption'].head()

date_placed = dfs['placed_for_adoption']

date_placed


date_placed['DATE_PLACED_dt'] = pd.to_datetime(date_placed['DATE_PLACED'], format='%d/%m/%Y', errors='coerce')

date_placed

invalid_dobss = date_placed['DATE_PLACED_dt'].isna()

error_rows1 = date_placed[invalid_dobss]

error_rows1

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt
29,bad_entry_1,Not a date,This isn't a valid date,This also isn't a date,oop,NaT

In [5]:
# 115 - Date of Local Authority's (LA) decision that a child 
# should be placed for adoption is not a valid date."

# select the placed for adoption table from dfs, 
# convert the correct column to a datetime, 
# make the slice

adoption = dfs['placed_for_adoption']

adoption['DATE_PLACED_dt'] = pd.to_datetime(adoption['DATE_PLACED'], format="%d/%m/%Y", errors='coerce')

invalid_placed_for_adoption_dates = adoption['DATE_PLACED_dt'].isna()

p4a_errors = adoption[invalid_placed_for_adoption_dates]

p4a_errors

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt
29,bad_entry_1,Not a date,This isn't a valid date,This also isn't a date,oop,NaT

In [6]:
print(header['ETHNIC'].unique().tolist())
header['ETHNIC'].value_counts()

['WROM', 'REFU', 'ABAN', 'AOTH', 'WBRI', 'WIRI', 'MOTH', 'NOBT', 'WIRT', 'MWBA', 'MWAS', 'APKN', 'BOTH', 'OOTH', 'WOTH', 'BCRB', 'MWBC', 'AIND', 'CHNE', 'BAFR', 'Alien']

ETHNIC
REFU     148
MWBA     148
WBRI     146
OOTH     146
WOTH     144
MWBC     142
WIRT     139
ABAN     138
BAFR     138
AIND     137
AOTH     133
MWAS     133
BOTH     131
BCRB     129
MOTH     128
APKN     127
WROM     124
NOBT     117
WIRI     115
CHNE     112
Alien      1
Name: count, dtype: int64

In [7]:
# .isin() -> returns true where a column has a value in a list... it is in the list
# 103 - The ethnicity code is either not valid or has not been entered.

ethncity_codes = [
        "WBRI",
        "WIRI",
        "WOTH",
        "WIRT",
        "WROM",
        "MWBC",
        "MWBA",
        "MWAS",
        "MOTH",
        "AIND",
        "APKN",
        "ABAN",
        "AOTH",
        "BCRB",
        "BAFR",
        "BOTH",
        "CHNE",
        "OOTH",
        "REFU",
        "NOBT",
    ]
# ~ 
error_rows = header[~header['ETHNIC'].isin(ethncity_codes)]
error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [8]:
dfs.keys()
#dfs['ad1'].info()
#dfs['ad1']['FOSTER_CARE'].unique().count(axis=1)

dfs['ad1']['FOSTER_CARE'].value_counts()

FOSTER_CARE
0      17
1      12
777     1
Name: count, dtype: int64

In [9]:
ad1 = dfs['ad1']

ad1

#error_rows2 = ad1[ad1['FOSTER_CARE'].isin(["0","1"])]

#error_rows2 = ad1[~ad1['FOSTER_CARE'].isin([0,1])]
ad1['FOSTER_CARE'] = ad1['FOSTER_CARE'].astype('str')

#error_rows2 = ad1[~ad1['FOSTER_CARE'].isin([0,1])]

error_rows2 = ad1[~ad1['FOSTER_CARE'].isin(["0","1"])]

error_rows2

,CHILD,DOB,DATE_INT,DATE_MATCH,FOSTER_CARE,NB_ADOPTR,SEX_ADOPTR,LS_ADOPTR
29,bad_entry,datedate,notdate,datenot,777,Q,Will,let's go

In [10]:
# 114 - Data entry to record the status of former carer(s) of an adopted child is invalid.
# When we do an isin we need to check the datatype of the list is the same as the values
# valid codes 0, 1
# table is ad1

header

,CHILD,SEX,DOB,ETHNIC,UPN,MOTHER,MC_DOB,DOB_dt
0,566910,2,27/03/2008,WROM,D051910639385,NaN,NaN,2008-03-27
1,384923,2,09/09/2011,REFU,L034811502612,NaN,NaN,2011-09-09
2,709901,1,14/02/2013,ABAN,Y021751958510,NaN,NaN,2013-02-14
3,550084,2,04/05/2008,AOTH,R095578985099,NaN,NaN,2008-05-04
4,710229,2,15/04/2002,REFU,Z095096287583,NaN,NaN,2002-04-15
...,...,...,...,...,...,...,...,...
2671,481370,2,12/02/2008,BAFR,C014150452081,NaN,NaN,2008-02-12
2672,791577,1,28/05/2011,WBRI,Q009369089812,NaN,NaN,2011-05-28
2673,238470,1,21/11/2013,AIND,P095222532769,NaN,NaN,2013-11-21
2674,437361,1,15/12/2012,WROM,G018001328504,NaN,NaN,2012-12-15
2675,bad_entry_1,7,oops!,Alien,UPDOG,NaN,NaN,NaT

In [11]:
merged_df = date_placed.merge(header[['CHILD', 'DOB_dt']], on='CHILD', how='left', suffixes=[None, '_head'])

merged_df

,CHILD,DOB,DATE_PLACED,DATE_PLACED_CEASED,REASON_PLACED_CEASED,DATE_PLACED_dt,DOB_dt
0,988635,15/06/2013,22/11/2015,07/04/2017,XXX,2015-11-22,2013-06-15
1,161125,24/07/2002,08/05/2015,24/02/2018,XXX,2015-05-08,2002-07-24
2,590545,24/11/2008,12/09/2015,23/04/2017,XXX,2015-09-12,2008-11-24
3,757606,12/12/2003,16/09/2015,23/02/2018,XXX,2015-09-16,2003-12-12
4,921450,11/10/2006,02/03/2015,15/08/2017,XXX,2015-03-02,2006-10-11
5,4022,11/05/2001,11/11/2015,30/12/2017,XXX,2015-11-11,2001-05-11
6,127650,24/02/2013,05/09/2015,22/06/2017,XXX,2015-09-05,2013-02-24
7,624227,04/07/2008,27/01/2015,24/09/2017,XXX,2015-01-27,2008-07-04
8,711458,06/05/2009,19/03/2015,27/11/2017,XXX,2015-03-19,2009-05-06
9,549562,25/07/2009,30/10/2015,22/11/2017,XXX,2015-10-30,2009-07-25
10,83008,05/06/2005,06/02/2015,16/10/2017,XXX,2015-02-06,2005-06-05
11,764585,01/06/2011,17/05/2015,08/12/2017,XXX,2015-05-17,2011-06-01
12,432916,28/01/2002,02/08/2015,08/03/2018,XXX,2015-08-02,2002-01-28
13,232351,08/11/2006,09/10/2015,02/08/2017,XXX,2015-10-09,2006-11-08
14,682447,10/07/2008,02/01/2015,03/11/2017,XXX,2015-01-02,2008-07-10
15,979106,11/04/2013,04/02/2015,12/01/2018,XXX,2015-02-04,2013-04-11
16,177224,16/04/2008,17/01/2015,02/11/2017,XXX,2015-01-17,2008-04-16
17,150309,12/12/2003,22/04/2015,10/04/2017,XXX,2015-04-22,2003-12-12
18,912765,25/04/2007,24/06/2015,02/05/2017,XXX,2015-06-24,2007-04-25
19,258758,09/01/2012,10/06/2015,22/04/2017,XXX,2015-06-10,2012-01-09
20,183392,03/09/2012,28/03/2015,02/03/2018,XXX,2015-03-28,2012-09-03
21,882662,24/07/2003,26/09/2015,22/11/2017,XXX,2015-09-26,2003-07-24
22,867782,20/09/2002,02/09/2015,04/04/2017,XXX,2015-09-02,2002-09-20
23,398366,07/06/2010,17/03/2015,29/05/2017,XXX,2015-03-17,2010-06-07
24,465676,09/05/2012,30/05/2015,29/05/2017,XXX,2015-05-30,2012-05-09
25,553789,15/07/2010,06/12/2015,08/02/2018,XXX,2015-12-06,2010-07-15
26,667633,26/10/2007,01/06/2015,02/05/2017,XXX,2015-06-01,2007-10-26
27,940956,02/04/2011,30/01/2015,29/11/2017,XXX,2015-01-30,2011-04-02
28,458257,21/02/2007,23/08/2015,03/01/2018,XXX,2015-08-23,2007-02-21
29,bad_entry_1,Not a date,This isn't a valid date,This also isn't a date,oop,NaT,NaT

In [12]:
# 184 - Date of decision that a child should be placed for adoption is before the child was born.
# return rows where DOB after DATE_PLACED -> DOB > DATE_PLACED



error_rows = merged_df[merged_df["DOB_dt"] > merged_df['DATE_PLACED_dt']]

error_rows

Empty DataFrame
Columns: [CHILD, DOB, DATE_PLACED, DATE_PLACED_CEASED, REASON_PLACED_CEASED, DATE_PLACED_dt, DOB_dt]
Index: []

In [13]:
# 302 - First episode starts before child was born.
# tables are header and episodes
# DOB from header and DECOM from episodes

header = dfs['header']

# ssda903 102 - date of birth is not a valid date

# coercing errors returns NATs for invalid dates
# if I slice out all NaTs - I have all the invalid dates!
header['DOB_dt'] = pd.to_datetime(header['DOB'], format="%d/%m/%Y", errors='coerce')

# .isna() rewutnrs true where the value in a row in a column is an Na
invalid_dobs = header['DOB_dt'].isna()
error_rows = header[invalid_dobs]

error_rows

            CHILD  SEX    DOB ETHNIC    UPN  MOTHER MC_DOB DOB_dt
2675  bad_entry_1    7  oops!  Alien  UPDOG     NaN    NaN    NaT

In [21]:
# 302 - First episode starts before child was born.
# tables are header and episodes
# DOB from header and DECOM from episodes

episodes = dfs['episodes']


episodes['DECOM_dt'] = pd.to_datetime(episodes['DECOM'], format="%d/%m/%Y", errors='coerce')

episodes.isna().sum()



# sorts values
episodes = episodes.sort_values(['CHILD', 'DECOM_dt'], ascending=[True,False])

#episodes = episodes.sort_values(by=['CHILD', 'DECOM_dt'], ascending=[True,False])
#episodes


# drops duplicates
episodes.drop_duplicates('CHILD', keep='first', inplace=True)
#episodes



df = pd.merge(episodes, header, how='left', on='CHILD', suffixes=['_epi', '_hdr'])

#df_1 = episodes.merge(header, on='CHILD', how='left', suffixes=['_epi', '_hdr'])
episodes


error_rows = df[df['DECOM'] < df['DOB']]
error_rows

,CHILD,DECOM,RNE,LS,CIN,PLACE,PLACE_PROVIDER,DEC,REC,REASON_PLACE_CHANGE,...,PL_POST,URN,DECOM_dt,SEX,DOB,ETHNIC,UPN,MOTHER,MC_DOB,DOB_dt
0,32,12/02/2017,T,J1,N3,K2,PR1,15/04/2017,E3,NaN,...,WI5 9CC,7876040,2017-02-12,2,15/02/2008,WROM,N083906900567,NaN,NaN,2008-02-15
1,982,15/10/2017,P,E1,N7,S1,PR0,NaN,X1,CHILD,...,WG17 9FD,5730861,2017-10-15,2,21/11/2010,BOTH,V078668886875,NaN,NaN,2010-11-21
2,1243,02/01/2017,L,V4,N5,Z1,PR0,18/05/2017,E9,NaN,...,WC30 9OS,7270736,2017-01-02,1,19/08/2002,OOTH,U000920739425,NaN,NaN,2002-08-19
3,1407,07/10/2017,P,L2,N3,R5,PR5,NaN,E5,NaN,...,WF24 2BX,2347066,2017-10-07,2,26/06/2003,AOTH,Y010365886691,NaN,NaN,2003-06-26
4,2431,01/02/2018,P,L2,N3,A3,PR5,NaN,E14,NaN,...,WT6 3JM,8470650,2018-02-01,1,19/01/2001,MWBC,W079251598684,NaN,NaN,2001-01-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110,990781,14/11/2017,P,L3,N6,H5,PR3,NaN,X1,CLOSE,...,WX1 8MQ,9760420,2017-11-14,2,21/08/2006,MOTH,F079478559882,NaN,NaN,2006-08-21
2112,991062,06/09/2016,T,J1,N3,U6,PR1,07/04/2017,E14,NaN,...,WC22 6IS,7181943,2016-09-06,1,15/03/2013,CHNE,R066104779187,NaN,NaN,2013-03-15
2116,995881,02/03/2018,P,L1,N5,U5,PR0,NaN,X1,CREQO,...,WW14 9WU,9260444,2018-03-02,2,03/11/2004,REFU,X032007250701,NaN,NaN,2004-11-03
2118,997201,07/06/2017,T,L3,N4,A5,PR1,NaN,X1,NaN,...,WN12 2KE,2276120,2017-06-07,1,24/05/2006,WBRI,X075905131541,NaN,NaN,2006-05-24
2120,998192,08/07/2017,T,C2,N2,U1,PR4,NaN,X1,CREQB,...,WA22 6DB,1505258,2017-07-08,2,25/07/2007,AIND,P044466275725,NaN,NaN,2007-07-25

In [26]:
# sort_values()
# drop_duplicates()
 
epi_ordered = episodes.sort_values(['CHILD', 'DECOM_dt'], ascending=True)
epi_ordered
first_episode = epi_ordered.drop_duplicates('CHILD', keep='first')
 
first_episode

,CHILD,DECOM,RNE,LS,CIN,PLACE,PLACE_PROVIDER,DEC,REC,REASON_PLACE_CHANGE,HOME_POST,PL_POST,URN,DECOM_dt
4801,32,12/02/2017,T,J1,N3,K2,PR1,15/04/2017,E3,NaN,ED8 1OX,WI5 9CC,7876040,2017-02-12
4043,982,15/10/2017,P,E1,N7,S1,PR0,NaN,X1,CHILD,EC17 4FJ,WG17 9FD,5730861,2017-10-15
437,1243,02/01/2017,L,V4,N5,Z1,PR0,18/05/2017,E9,NaN,EC5 5MZ,WC30 9OS,7270736,2017-01-02
1797,1407,07/10/2017,P,L2,N3,R5,PR5,NaN,E5,NaN,ER8 5QR,WF24 2BX,2347066,2017-10-07
3851,2431,01/02/2018,P,L2,N3,A3,PR5,NaN,E14,NaN,EZ17 3GY,WT6 3JM,8470650,2018-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,997201,07/06/2017,T,L3,N4,A5,PR1,NaN,X1,NaN,EC16 9ZF,WN12 2KE,2276120,2017-06-07
2766,997445,20/06/2016,P,J1,N2,U3,PR3,24/09/2017,E48,NaN,EP2 2VO,WE6 1FZ,3786993,2016-06-20
155,998192,08/07/2017,T,C2,N2,U1,PR4,NaN,X1,CREQB,EL26 9FW,WA22 6DB,1505258,2017-07-08
157,998777,17/03/2018,P,C2,N2,T0,PR2,NaN,X1,CHILD,EZ22 1LU,WC14 7CT,9451857,2018-03-17
324,999397,29/08/2017,L,J2,N7,P2,PR1,NaN,E47,NaN,EC5 2KK,WV19 3SY,3534004,2017-08-29