In [2]:
print('hello')

hello

In [3]:
import pandas as pd

In [4]:
#import pandas as pd

filepath = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/1980%202023%20average%20house%20prices.csv"

house_prices = pd.read_csv(filepath)

house_prices

,Name,Period,House price index All property types,Average price All property types,Percentage change (monthly) All property types,Percentage change (yearly) All property types
0,United Kingdom,1980-01,10.11,19273,3.94,28.59
1,United Kingdom,1980-02,10.11,19273,3.94,28.59
2,United Kingdom,1980-03,10.11,19273,3.94,28.59
3,United Kingdom,1980-04,10.51,20044,4.00,24.15
4,United Kingdom,1980-05,10.51,20044,4.00,24.15
...,...,...,...,...,...,...
518,United Kingdom,2023-03,148.20,282548,-1.00,3.20
519,United Kingdom,2023-04,148.90,283871,0.50,2.50
520,United Kingdom,2023-05,149.50,285053,0.40,1.60
521,United Kingdom,2023-06,151.20,288281,1.10,1.90
522,United Kingdom,2023-07,152.00,289824,0.50,0.60

In [5]:
house_prices["Period_dt"] = pd.to_datetime(house_prices["Period"], format="%Y-%m")

house_prices["Period_dt"].info()

house_prices

<class 'pandas.core.series.Series'>
RangeIndex: 523 entries, 0 to 522
Series name: Period_dt
Non-Null Count  Dtype
--------------  -----
523 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 4.2 KB

,Name,Period,House price index All property types,Average price All property types,Percentage change (monthly) All property types,Percentage change (yearly) All property types,Period_dt
0,United Kingdom,1980-01,10.11,19273,3.94,28.59,1980-01-01
1,United Kingdom,1980-02,10.11,19273,3.94,28.59,1980-02-01
2,United Kingdom,1980-03,10.11,19273,3.94,28.59,1980-03-01
3,United Kingdom,1980-04,10.51,20044,4.00,24.15,1980-04-01
4,United Kingdom,1980-05,10.51,20044,4.00,24.15,1980-05-01
...,...,...,...,...,...,...,...
518,United Kingdom,2023-03,148.20,282548,-1.00,3.20,2023-03-01
519,United Kingdom,2023-04,148.90,283871,0.50,2.50,2023-04-01
520,United Kingdom,2023-05,149.50,285053,0.40,1.60,2023-05-01
521,United Kingdom,2023-06,151.20,288281,1.10,1.90,2023-06-01
522,United Kingdom,2023-07,152.00,289824,0.50,0.60,2023-07-01

In [6]:
filepath2 = r"https://raw.githubusercontent.com/data-to-insight/ERN-sessions/main/data/ChildIdentifiers.csv"

ci = pd.read_csv(filepath2)

ci

print(ci.info())
print(ci.head())
print(ci.tail())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               332 non-null    int64
 1   LAchildID                332 non-null    object
 2   UPN                      332 non-null    object
 3   FormerUPN                0 non-null      float64
 4   UPNunknown               0 non-null      float64
 5   PersonBirthDate          332 non-null    object
 6   ExpectedPersonBirthDate  7 non-null      object
 7   GenderCurrent            332 non-null    int64
 8   PersonDeathDate          21 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 23.5+ KB
None
   Unnamed: 0        LAchildID            UPN  FormerUPN  UPNunknown  \
0           0  RND000215205141  A850728973744        NaN         NaN
1           1  RND000824303014  A141396438491        NaN         NaN
2           2  RND000750143123  A929946861554        NaN         NaN
3           3  RND000909164501  A612330267292        NaN         NaN
4           4  RND000382171815  A604459366806        NaN         NaN

  PersonBirthDate ExpectedPersonBirthDate  GenderCurrent PersonDeathDate
0      2019-12-06                     NaN              1             NaN
1      2011-04-27                     NaN              9             NaN
2      2017-06-06              2019-12-06              1             NaN
3      2014-10-03                     NaN              0             NaN
4      2019-09-25                     NaN              2             NaN
     Unnamed: 0        LAchildID            UPN  FormerUPN  UPNunknown  \
327         327  RND000112711501  A465246916125        NaN         NaN
328         328  RND000513120794  A540014111973        NaN         NaN
329         329  RND000541643134  A549582689058        NaN         NaN
330         330  RND000404939452  A889492349196        NaN         NaN
331         331  RND000589802835  A877624860226        NaN         NaN

    PersonBirthDate ExpectedPersonBirthDate  GenderCurrent PersonDeathDate
327      2010-07-07                     NaN              2             NaN
328      2018-08-14                     NaN              2             NaN
329      2021-12-09                     NaN             51             NaN
330      2013-07-23                     NaN              2             NaN
331      2021-10-25                     NaN              9             NaN

In [7]:
ci["PersonBirthDate_dt"] = pd.to_datetime(ci["PersonBirthDate"], format = "%Y-%m-%d")
ci["ExpectedPersonBirthDate_dt"] = pd.to_datetime(ci["ExpectedPersonBirthDate"],format = "%Y-%m-%d")

ci

,Unnamed: 0,LAchildID,UPN,FormerUPN,UPNunknown,PersonBirthDate,ExpectedPersonBirthDate,GenderCurrent,PersonDeathDate,PersonBirthDate_dt,ExpectedPersonBirthDate_dt
0,0,RND000215205141,A850728973744,NaN,NaN,2019-12-06,NaN,1,NaN,2019-12-06,NaT
1,1,RND000824303014,A141396438491,NaN,NaN,2011-04-27,NaN,9,NaN,2011-04-27,NaT
2,2,RND000750143123,A929946861554,NaN,NaN,2017-06-06,2019-12-06,1,NaN,2017-06-06,2019-12-06
3,3,RND000909164501,A612330267292,NaN,NaN,2014-10-03,NaN,0,NaN,2014-10-03,NaT
4,4,RND000382171815,A604459366806,NaN,NaN,2019-09-25,NaN,2,NaN,2019-09-25,NaT
...,...,...,...,...,...,...,...,...,...,...,...
327,327,RND000112711501,A465246916125,NaN,NaN,2010-07-07,NaN,2,NaN,2010-07-07,NaT
328,328,RND000513120794,A540014111973,NaN,NaN,2018-08-14,NaN,2,NaN,2018-08-14,NaT
329,329,RND000541643134,A549582689058,NaN,NaN,2021-12-09,NaN,51,NaN,2021-12-09,NaT
330,330,RND000404939452,A889492349196,NaN,NaN,2013-07-23,NaN,2,NaN,2013-07-23,NaT
331,331,RND000589802835,A877624860226,NaN,NaN,2021-10-25,NaN,9,NaN,2021-10-25,NaT

In [8]:
house_prices_monthly_change_sum = house_prices["Percentage change (monthly) All property types"].sum()

print(f"The sum of percentage is : {house_prices_monthly_change_sum}")

The sum of percentage is : 623.29

In [14]:
ci

ci["PersonBirthDate_dt"]
collection_end = pd.to_datetime("31/03/2026", format ="%d/%m/%Y")

ci["age_de"] = collection_end - ci["PersonBirthDate_dt"]

ci

ci["PersonBirthDate_dt"]

collection_end = pd.to_datetime("31/03/2026", format="%d/%m/%Y")

ci["age_delta"] = collection_end - ci["PersonBirthDate_dt"]

ci["age_delta"] = ci["age_delta"] / pd.Timedelta(365.25, "d")

ci["age_delta"] = ci["age_delta"].astype("int")

ci["age_delta"]

0       6
1      14
2       8
3      11
4       6
       ..
327    15
328     7
329     4
330    12
331     4
Name: age_delta, Length: 332, dtype: int64